apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: DevOps_Beta
    service.beta.kubernetes.io/azure-load-balancer-ipv4: AZURE_PUBLIC_IP
    service.beta.kubernetes.io/azure-dns-label-name: welcome
spec:
  selector:
    app: welcome-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: LoadBalancer